export { default as Header } from "./Header/Header";
export { default as Footer } from "./Footer/Footer";
export { default as Button } from "./Button/Button";
export { default as Text } from "./Text/Text";
export { default as Card } from "./Card/Card";
export { default as Products } from "./Products/Products";
export { default as Heading } from "./Heading/Heading";
export { default as Partners } from "./Partners/Partners";
export { default as Hero } from "./Hero/Hero";
export { default as Contact } from "./Contact/Contact";
export { default as PatientCard } from "./PatientCard/PatientCard";
export { default as ResultsTable } from './ResultsTable/ResultsTable'
export { default as ScoringTable } from './ScoringTable/ScoringTable'
export { default as ResultsCharts } from './ResultsChart/ResultsCharts'
export { default as ResultsChartAge } from './ResultsChartAge/ResultsChartAge'
export { default as Loading } from './Loading/Loading'
export { default as FileInputBox } from './FileInputBox/FileInputBox'
export { default as PatientInput } from './PatientInput/PatientInput'
export { default as Progress } from './Progress/Progress';
